// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// GEDI_new
SEXP GEDI_new(List params, List aux, List target, List hyperparams, int verbose, int num_threads);
RcppExport SEXP _gedi_GEDI_new(SEXP paramsSEXP, SEXP auxSEXP, SEXP targetSEXP, SEXP hyperparamsSEXP, SEXP verboseSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< List >::type aux(auxSEXP);
    Rcpp::traits::input_parameter< List >::type target(targetSEXP);
    Rcpp::traits::input_parameter< List >::type hyperparams(hyperparamsSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(GEDI_new(params, aux, target, hyperparams, verbose, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// GEDI_initialize
List GEDI_initialize(SEXP model_ptr, bool multimodal);
RcppExport SEXP _gedi_GEDI_initialize(SEXP model_ptrSEXP, SEXP multimodalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    Rcpp::traits::input_parameter< bool >::type multimodal(multimodalSEXP);
    rcpp_result_gen = Rcpp::wrap(GEDI_initialize(model_ptr, multimodal));
    return rcpp_result_gen;
END_RCPP
}
// GEDI_optimize
List GEDI_optimize(SEXP model_ptr, int iterations, int track_interval);
RcppExport SEXP _gedi_GEDI_optimize(SEXP model_ptrSEXP, SEXP iterationsSEXP, SEXP track_intervalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type track_interval(track_intervalSEXP);
    rcpp_result_gen = Rcpp::wrap(GEDI_optimize(model_ptr, iterations, track_interval));
    return rcpp_result_gen;
END_RCPP
}
// GEDI_train
List GEDI_train(SEXP model_ptr, int iterations, int track_interval, bool multimodal);
RcppExport SEXP _gedi_GEDI_train(SEXP model_ptrSEXP, SEXP iterationsSEXP, SEXP track_intervalSEXP, SEXP multimodalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type track_interval(track_intervalSEXP);
    Rcpp::traits::input_parameter< bool >::type multimodal(multimodalSEXP);
    rcpp_result_gen = Rcpp::wrap(GEDI_train(model_ptr, iterations, track_interval, multimodal));
    return rcpp_result_gen;
END_RCPP
}
// compute_s_0_dense
Eigen::VectorXd compute_s_0_dense(const Eigen::Map<Eigen::VectorXd>& J_vec, const Eigen::Map<Eigen::MatrixXd>& Y, double J);
RcppExport SEXP _gedi_compute_s_0_dense(SEXP J_vecSEXP, SEXP YSEXP, SEXP JSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type J_vec(J_vecSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type J(JSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_s_0_dense(J_vec, Y, J));
    return rcpp_result_gen;
END_RCPP
}
// compute_Yp
Eigen::SparseMatrix<double> compute_Yp(const Eigen::MappedSparseMatrix<double>& Y, const Eigen::Map<Eigen::VectorXd>& J_vec, const Eigen::Map<Eigen::VectorXd>& s_0);
RcppExport SEXP _gedi_compute_Yp(SEXP YSEXP, SEXP J_vecSEXP, SEXP s_0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type J_vec(J_vecSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type s_0(s_0SEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Yp(Y, J_vec, s_0));
    return rcpp_result_gen;
END_RCPP
}
// compute_o_0_dense
Eigen::VectorXd compute_o_0_dense(const Eigen::Map<Eigen::MatrixXd>& Yp, const Eigen::Map<Eigen::VectorXd>& N_vec, double N);
RcppExport SEXP _gedi_compute_o_0_dense(SEXP YpSEXP, SEXP N_vecSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type Yp(YpSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type N_vec(N_vecSEXP);
    Rcpp::traits::input_parameter< double >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_o_0_dense(Yp, N_vec, N));
    return rcpp_result_gen;
END_RCPP
}
// compute_Yp_dense
Eigen::MatrixXd compute_Yp_dense(const Eigen::Map<Eigen::MatrixXd>& Y, const Eigen::Map<Eigen::VectorXd>& J_vec, const Eigen::Map<Eigen::VectorXd>& s_0);
RcppExport SEXP _gedi_compute_Yp_dense(SEXP YSEXP, SEXP J_vecSEXP, SEXP s_0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type J_vec(J_vecSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type s_0(s_0SEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Yp_dense(Y, J_vec, s_0));
    return rcpp_result_gen;
END_RCPP
}
// VecVecProduct
Eigen::MatrixXd VecVecProduct(const Eigen::Map<Eigen::VectorXd>& a, const Eigen::Map<Eigen::VectorXd>& b);
RcppExport SEXP _gedi_VecVecProduct(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(VecVecProduct(a, b));
    return rcpp_result_gen;
END_RCPP
}
// MatVecProduct
Eigen::VectorXd MatVecProduct(const Eigen::Map<Eigen::MatrixXd>& A, const Eigen::Map<Eigen::VectorXd>& b);
RcppExport SEXP _gedi_MatVecProduct(SEXP ASEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(MatVecProduct(A, b));
    return rcpp_result_gen;
END_RCPP
}
// eigenSparseMatVecProduct
Eigen::VectorXd eigenSparseMatVecProduct(const Eigen::MappedSparseMatrix<double>& A, const Eigen::Map<Eigen::VectorXd>& b);
RcppExport SEXP _gedi_eigenSparseMatVecProduct(SEXP ASEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(eigenSparseMatVecProduct(A, b));
    return rcpp_result_gen;
END_RCPP
}
// compute_Mp
Eigen::SparseMatrix<double> compute_Mp(const Eigen::MappedSparseMatrix<double> M, const Eigen::Map<Eigen::VectorXd> J_vec, const Eigen::Map<Eigen::VectorXd> s_0);
RcppExport SEXP _gedi_compute_Mp(SEXP MSEXP, SEXP J_vecSEXP, SEXP s_0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double> >::type M(MSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type J_vec(J_vecSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type s_0(s_0SEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Mp(M, J_vec, s_0));
    return rcpp_result_gen;
END_RCPP
}
// compute_s_0
Eigen::VectorXd compute_s_0(const Eigen::Map<Eigen::VectorXd> J_vec, const Eigen::MappedSparseMatrix<double> M, double J);
RcppExport SEXP _gedi_compute_s_0(SEXP J_vecSEXP, SEXP MSEXP, SEXP JSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type J_vec(J_vecSEXP);
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double> >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type J(JSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_s_0(J_vec, M, J));
    return rcpp_result_gen;
END_RCPP
}
// compute_o_0
Eigen::VectorXd compute_o_0(const Eigen::MappedSparseMatrix<double> Mp, const Eigen::Map<Eigen::VectorXd> N_vec, double N);
RcppExport SEXP _gedi_compute_o_0(SEXP MpSEXP, SEXP N_vecSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double> >::type Mp(MpSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type N_vec(N_vecSEXP);
    Rcpp::traits::input_parameter< double >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_o_0(Mp, N_vec, N));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gedi_GEDI_new", (DL_FUNC) &_gedi_GEDI_new, 6},
    {"_gedi_GEDI_initialize", (DL_FUNC) &_gedi_GEDI_initialize, 2},
    {"_gedi_GEDI_optimize", (DL_FUNC) &_gedi_GEDI_optimize, 3},
    {"_gedi_GEDI_train", (DL_FUNC) &_gedi_GEDI_train, 4},
    {"_gedi_compute_s_0_dense", (DL_FUNC) &_gedi_compute_s_0_dense, 3},
    {"_gedi_compute_Yp", (DL_FUNC) &_gedi_compute_Yp, 3},
    {"_gedi_compute_o_0_dense", (DL_FUNC) &_gedi_compute_o_0_dense, 3},
    {"_gedi_compute_Yp_dense", (DL_FUNC) &_gedi_compute_Yp_dense, 3},
    {"_gedi_VecVecProduct", (DL_FUNC) &_gedi_VecVecProduct, 2},
    {"_gedi_MatVecProduct", (DL_FUNC) &_gedi_MatVecProduct, 2},
    {"_gedi_eigenSparseMatVecProduct", (DL_FUNC) &_gedi_eigenSparseMatVecProduct, 2},
    {"_gedi_compute_Mp", (DL_FUNC) &_gedi_compute_Mp, 3},
    {"_gedi_compute_s_0", (DL_FUNC) &_gedi_compute_s_0, 3},
    {"_gedi_compute_o_0", (DL_FUNC) &_gedi_compute_o_0, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_gedi(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
